function [StructuredData ] = Structure_Output_Data( fn, capture_iter )
% This function converts the output files of Electron Back Scattered
% Diffraction
% experimental data generated by Ali in Surya Kalidindi's MINED group at Georgia Tech.
% The flat files are converted into a structure than can be easily written
% to HDF5. The HDF5 and are available on Tony Fast's public Dropbox for 
% consumption.
%
% The output files are unstructured flat files containing

% Open the unstructured data for read.

prec = '%f %f %f %f %f %f %f %f %i %i %*s\n';
fo = fopen( fn, 'r' );

s = fgetl( fo );
while s(1) == '#'
    s = fgetl( fo );
end
ct = 0;

D = fscanf( fo, prec, [10 Inf]);
D = [sscanf( s, prec ), D]';

xx = unique( single( D(:,4)));
yy = unique( single( D(:,5)));

n = [numel(xx) numel(yy)];

[~,xxi] = ismember( D(:,4), xx );
[~,yyi] = ismember( D(:,5), yy );



I = reshape( sub2ind( [ max( xxi), max(yyi)],xxi,yyi), n);
StructuredData.Spatial(1).phi1 = zeros( n );
StructuredData.Spatial(1).phi1(I) = D(:,1);
StructuredData.Spatial(1).PHI = zeros(n);
StructuredData.Spatial(1).PHI(I) = D(:,2);
StructuredData.Spatial(1).phi2 = zeros(n);
StructuredData.Spatial(1).phi2(I) = D(:,3);
StructuredData.Spatial(1).IQuality = zeros(n);
StructuredData.Spatial(1).IQuality(I) = D(:,6);
StructuredData.Spatial(1).Confidence = zeros(n);
StructuredData.Spatial(1).Confidence(I) = D(:,7);
StructuredData.Spatial(1).Fit = zeros(n);
StructuredData.Spatial(1).Fit(I) = D(:,8);
StructuredData.Spatial(1).ID = zeros(n);
StructuredData.Spatial(1).ID(I) = D(:,9);
fclose( fo );